#!/bin/env/bash php

<?php
require_once __DIR__.'/bootstrap.php'; # Load the bootstrap file

use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\RFCValidation;
use Egulias\EmailValidator\Validation\DNSCheckValidation;
use Egulias\EmailValidator\Validation\MultipleValidationWithAnd;

array_shift($argv); # Remove the script name from the arguments array

if ( count($argv) < 1 ) {
    echo "Usage: php mail-validator.php <email>\n";
    exit(1);
}

$email = $argv[0]; # Get the email address from the command line argument 

$validator = new EmailValidator();
$multipleValidations = new MultipleValidationWithAnd([
    new RFCValidation(),
    new DNSCheckValidation()
]);
$response = $validator->isValid( $email, $multipleValidations );

if ( $response ) {
    echo "The email address '$email' is valid.\n";
} else {
    echo "The email address '$email' is invalid.\n";
} 


